In [3]:
import numpy as np

## Datatypes and attributes

In [4]:
# Numpy main datatype in ndarray-n dimensional array
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[2,3,4], 
             [4,6,3.3]])
a3 = np.array([[[1,2,3],
              [4,5,6], 
              [7,8,9]],
              [[10, 11, 12], 
               [13, 14, 15], 
               [16, 17, 18]]])

In [7]:
a2

array([[2. , 3. , 4. ],
       [4. , 6. , 3.3]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim #number of dimensions, comma seperated

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)


(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
# create a data frame from numpy array
import pandas as pd
df= pd.DataFrame(a2)

In [17]:
df

0    1    2
0  2.0  3.0  4.0
1  4.0  6.0  3.3

## How to create numpy arrays

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
ones=np.ones((2,3))#shift and tab inside the () opens the signature of that function

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array= np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array=np.random.randint(0, 10, (3,5))
random_array

array([[4, 7, 6, 7, 0],
       [7, 7, 0, 3, 7],
       [0, 9, 1, 1, 4]], dtype=int32)

In [26]:
random_array2=np.random.random((5,3))
random_array2

array([[0.65668588, 0.38333498, 0.90515095],
       [0.34645728, 0.84581335, 0.586361  ],
       [0.19312869, 0.45271407, 0.30398918],
       [0.10676462, 0.1193141 , 0.19210974],
       [0.36623068, 0.89801644, 0.10647827]])

In [27]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.40198823, 0.11542885, 0.90069025],
       [0.38023908, 0.7981135 , 0.51965578],
       [0.26000868, 0.79798348, 0.09074741],
       [0.28257312, 0.11763558, 0.96085689],
       [0.14028145, 0.60726079, 0.36709162]])

In [28]:
# pseudo random numbers
np.random.seed(seed=4)#this gives random numbers alligned with the seeds
random_array4= np.random.randint(0, 10, (5,3))
random_array4

array([[7, 5, 1],
       [8, 7, 8],
       [2, 9, 7],
       [7, 7, 9],
       [8, 4, 2]], dtype=int32)

In [29]:
np.random.seed(7)#if you see a seed, then always allign with the seed
random_array5=np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing Arrays and Matrices

In [30]:
random_array4

array([[7, 5, 1],
       [8, 7, 8],
       [2, 9, 7],
       [7, 7, 9],
       [8, 4, 2]], dtype=int32)

In [31]:
np.unique(random_array4)

array([1, 2, 4, 5, 7, 8, 9], dtype=int32)

In [32]:
a1

array([1, 2, 3])

In [33]:
a2

array([[2. , 3. , 4. ],
       [4. , 6. , 3.3]])

In [34]:
a3


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a2[0]

array([2., 3., 4.])

In [36]:
a3.shape

(2, 3, 3)

In [37]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a2[1]

array([4. , 6. , 3.3])

In [39]:
a3[:1, :2, :3]

array([[[1, 2, 3],
        [4, 5, 6]]])

In [40]:
a4 = np.random.randint(0, 15, (2,3,4,5))#count backwards for visuals, 5 to columns, then 4 to inner rows

In [41]:
a4, a4.shape, a4.ndim

(array([[[[ 3, 12, 12,  5,  8],
          [ 8,  7,  5,  0, 11],
          [13,  0,  2,  8,  9],
          [14,  6,  4, 14,  9]],
 
         [[ 7,  3,  3,  8,  3],
          [ 0,  1,  0,  0,  6],
          [13, 12, 12, 12,  7],
          [ 7, 10,  9,  3,  0]],
 
         [[13,  7,  7, 12,  7],
          [ 0,  5,  4,  3,  1],
          [ 3, 11, 11,  1,  3],
          [11,  4,  3,  1, 11]]],
 
 
        [[[14,  9,  5,  9, 13],
          [ 1,  2,  3,  2,  2],
          [ 5,  7,  3, 11, 10],
          [ 0, 12, 13, 11,  9]],
 
         [[ 9, 12,  3, 14, 14],
          [12,  4,  5, 12, 11],
          [ 3,  0,  4, 11,  8],
          [10, 10,  6, 11,  7]],
 
         [[13,  2,  7,  3, 13],
          [12, 12, 13,  8,  6],
          [ 6,  5,  6,  5, 12],
          [11,  7,  1, 10,  5]]]], dtype=int32),
 (2, 3, 4, 5),
 4)

In [42]:
a4[1:2, :1, :1, :5]

array([[[[14,  9,  5,  9, 13]]]], dtype=int32)

## Manipulating and comparing arrays 

### Arithematic 

In [43]:
ones=np.ones(3)
ones


array([1., 1., 1.])

In [44]:
a1

array([1, 2, 3])

In [45]:
a1+ones

array([2., 3., 4.])

In [46]:
a1-ones

array([0., 1., 2.])

In [47]:
a1*ones

array([1., 2., 3.])

In [48]:
a2

array([[2. , 3. , 4. ],
       [4. , 6. , 3.3]])

In [49]:
a1*a2

array([[ 2. ,  6. , 12. ],
       [ 4. , 12. ,  9.9]])

In [50]:
a1


array([1, 2, 3])

In [51]:
a2*a1

array([[ 2. ,  6. , 12. ],
       [ 4. , 12. ,  9.9]])

In [52]:
#smaller array is broadcast against the larger array, so that their shapes are compatible
#two arrays are compatible if one of them is 1 or both are equal

In [53]:
a2.reshape(2, 3)*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2, a3

In [ ]:
a2*a3.reshape(3,2,3)

In [ ]:
a3.reshape(3,2,3)

In [ ]:
a1/ones

In [ ]:
a2//a1, a2/a1

In [ ]:
a2**2 

In [ ]:
np.square(a2)

In [ ]:
np.add(a1, ones)

In [ ]:
a1%2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation
performing the same operation on a number of things

In [ ]:
list1=[1,2,3]
type(list1)

In [ ]:
sum(list1)

In [ ]:
a1, type(a1)

In [ ]:
np.sum(a1), sum(a1)# whats the point of these two things?

Use python methods on python datatypes and use numpy methods on ndarrays

In [ ]:
massive_array=np.random.random(10000)
massive_array[:10]

In [ ]:
%timeit sum(massive_array)#python sum
%timeit np.sum(massive_array)#numpy sum

In [ ]:
42500/41.5 #times faster

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2), np.min(a2), np.std(a2), np.var(a2) #var: measure of the average degree to which each number is different from the mean
#Std: a measure of how spread out a group of numbers is from mean, how far away is every number from mean on average

In [ ]:
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and variance 
high_var_array = np.array([1,3,7,19, 30, 100, 230, 513])
low_var_array=np.array([1,3,6,8,11,15])

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

### Reshape and Transposing

In [ ]:
# a2*a3 didnt work bcs of size difference- 2,3 and 2,3,3

In [56]:
a2_reshape=a2.reshape(2,3,1) #

In [55]:
a3.shape

(2, 3, 3)

In [57]:
a2_reshape* a3 # JUST becasue your array comes in a certain shape doesnt mean you cant change it 

array([[[ 2. ,  4. ,  6. ],
        [12. , 15. , 18. ],
        [28. , 32. , 36. ]],

       [[40. , 44. , 48. ],
        [78. , 84. , 90. ],
        [52.8, 56.1, 59.4]]])

In [59]:
a2.T, a2.T.shape

(array([[2. , 4. ],
        [3. , 6. ],
        [4. , 3.3]]),
 (3, 2))

In [61]:
a3.T.shape, a3.T #flips the axis

((3, 3, 2),
 array([[[ 1, 10],
         [ 4, 13],
         [ 7, 16]],
 
        [[ 2, 11],
         [ 5, 14],
         [ 8, 17]],
 
        [[ 3, 12],
         [ 6, 15],
         [ 9, 18]]]))

### Dot Product
another way of finding patterns between two dif sets of data

In [63]:
np.random.seed(0)

m1=np.random.randint(0, 10, (5,3))
m2=np.random.randint(0, 10, (5,3))

In [65]:
m1, m2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]], dtype=int32),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]], dtype=int32))

In [66]:
m1*m2 #element wise multiplication, Hadamard product

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]], dtype=int32)

In [67]:
# dot Product
np.dot(m1, m2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [68]:
np.dot(m1.T, m2) 

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]], dtype=int32)

In [69]:
np.dot(m1, m2.T) 

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]], dtype=int32)

### Dot Product example

In [71]:
np.random.seed(0)

sales=np.random.randint(0, 20, (5,3))
sales

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [73]:
weeklySales=pd.DataFrame(sales, index=['Mon', 'Tues', 'Wed', 'Thurs', 'Frid'], columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])

In [74]:
weeklySales

Almond Butter  Peanut Butter  Cashew Butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Frid               1              6              7

In [75]:
price=np.array([10, 8, 12])

In [82]:
butterPrices= pd.DataFrame(price.reshape(1, 3), index=['Price'], columns=['Almond Butter', 'Peanut Butter', 'Cashew Butter'])

In [83]:
butterPrices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [86]:
totalSales=np.dot(sales, price)
totalSales

array([240, 138, 458, 232, 142])

In [87]:
butterPrices.shape, weeklySales.shape

((1, 3), (5, 3))

In [89]:
dailySales= butterPrices.dot(weeklySales.T) # this is pandas dot
dailySales 

Mon  Tues  Wed  Thurs  Frid
Price  240   138  458    232   142

In [91]:
weeklySales['Price $']=dailySales.T

In [92]:
weeklySales

Almond Butter  Peanut Butter  Cashew Butter  Price $
Mon               12             15              0      240
Tues               3              3              7      138
Wed                9             19             18      458
Thurs              4              6             12      232
Frid               1              6              7      142

### Comparison Operators

In [94]:
a1

array([1, 2, 3])

In [100]:
b1=np.array([[1,2,3], [4,5,6]])

In [102]:
boolarray =a1 >= b1

In [107]:
type(boolarray), boolarray.dtype

(numpy.ndarray, dtype('bool'))

In [108]:
a1 == b1

array([[ True,  True,  True],
       [False, False, False]])

In [109]:
#try out numpy comparison operators: all, any, less..., 

## Sorting Arrays

In [110]:
random_array

array([[4, 7, 6, 7, 0],
       [7, 7, 0, 3, 7],
       [0, 9, 1, 1, 4]], dtype=int32)

In [119]:
 np.sort(random_array, 0)# sorts rows if 1(default), cols if 0

array([[0, 7, 0, 1, 0],
       [4, 7, 1, 3, 4],
       [7, 9, 6, 7, 7]], dtype=int32)

In [114]:
np.argsort(random_array)#indexes of the sorted numb

array([[4, 0, 2, 1, 3],
       [2, 3, 0, 1, 4],
       [0, 2, 3, 4, 1]])

In [115]:
np.argmin(a1), np.argmax(a1)

(np.int64(0), np.int64(2))

In [117]:
np.argmax(random_array, 0) # 0 is axis 0, i.e in each column, while 1 would be row, in each row

array([1, 2, 0, 0, 1])

## Practical example- Numpy in Action

In [121]:
# <img src="panda.png"/>  this didnt not work

SyntaxError: invalid syntax (3916685497.py, line 1)

![ ](panda.png)

In [124]:
# Turn image into a numpy array
from matplotlib.image import imread

panda = imread('panda.png')
print(type(panda))

<class 'numpy.ndarray'>


In [125]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [130]:
panda.size, panda.shape, panda.ndim #the 3 is for the red, blue and gree ratio of every pixel

(24465000, (2330, 3500, 3), 3)

![ ](car-photo.png)

In [128]:
car= imread('car-photo.png')

In [129]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

![ ](dog-photo.png)

In [132]:
dog=imread('dog-photo.png')

In [133]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274