In [1]:
import numpy as np

## Datatypes and attributes

In [3]:
# Numpy main datatype in ndarray-n dimensional array
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[2,3,4], 
             [4,6,3.3]])
a3 = np.array([[[1,2,3],
              [4,5,6], 
              [7,8,9]],
              [[10, 11, 12], 
               [13, 14, 15], 
               [16, 17, 18]]])

In [8]:
a2

array([[2. , 3. , 4. ],
       [4. , 6. , 3.3]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [14]:
a1.ndim, a2.ndim, a3.ndim #number of dimensions, comma seperated

(1, 2, 3)

In [15]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [16]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [17]:
type(a1), type(a2), type(a3)


(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [19]:
# create a data frame from numpy array
import pandas as pd
df= pd.DataFrame(a2)

In [20]:
df

0    1    2
0  2.0  3.0  4.0
1  4.0  6.0  3.3

## How to create numpy arrays

In [23]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [24]:
ones=np.ones((2,3))#shift and tab inside the () opens the signature of that function

In [25]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [29]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_array= np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [32]:
random_array=np.random.randint(0, 10, (3,5))
random_array

array([[4, 5, 7, 0, 2],
       [9, 9, 4, 6, 3],
       [6, 1, 9, 1, 0]], dtype=int32)

In [34]:
random_array2=np.random.random((5,3))
random_array2

array([[0.8024066 , 0.4863611 , 0.20043014],
       [0.44228131, 0.17919015, 0.96222071],
       [0.43002912, 0.44007799, 0.04337059],
       [0.52880049, 0.66295945, 0.01670572],
       [0.20617811, 0.46306259, 0.39826153]])

In [36]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.94086371, 0.09186362, 0.12050008],
       [0.51439138, 0.45603544, 0.89662081],
       [0.25256079, 0.39560432, 0.46957155],
       [0.24988918, 0.79923766, 0.50430718],
       [0.88878737, 0.92129567, 0.83439645]])

In [ ]:
# pseudo random numbers
np.random.seed()