<a href="https://colab.research.google.com/github/alizehadeel/AI-ML-Notebook/blob/main/numpy-exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [23]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [24]:
# Create a 1-dimensional NumPy array using np.array()

a1=np.array([1,2,3,4,5])
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3], [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3], [4,5,6]], [[7,8,9], [0,1,2]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [25]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a1.ndim, a1.dtype, a1.size, type(a1) #dtype belongs to numpy and describes the data type, while type belongs to python and tells the type of the object-ndarray

(1, dtype('int64'), 5, numpy.ndarray)

In [26]:
# Attributes of 2-dimensional array
a2.ndim, a2.size, a2.dtype, type(a2)

(2, 6, dtype('int64'), numpy.ndarray)

In [27]:
# Attributes of 3-dimensional array
a3.size, a3.ndim, a3.dtype, type(a3)

(12, 3, dtype('int64'), numpy.ndarray)

In [28]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [29]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
# Create an array within a range of 0 and 100 with step 3
ranged=np.arange(0, 100, 3)
ranged

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [32]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
r1=np.random.randint(0, 10, (7,2))
r1

array([[0, 8],
       [6, 8],
       [7, 0],
       [7, 7],
       [2, 0],
       [7, 2],
       [2, 0]])

In [33]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
r2=np.random.random((3,5))
r2

array([[0.60595997, 0.92630088, 0.65107703, 0.91495968, 0.85003858],
       [0.44945067, 0.09541012, 0.37081825, 0.66884125, 0.66592236],
       [0.59129779, 0.27472179, 0.56124343, 0.38292687, 0.9717121 ]])

In [34]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
r3=np.random.randint(0, 10, (4,6))
r3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is? Same bcs the initial seed is the same.

In [35]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
r4=np.random.randint(1,10, (3,7))
# Find the unique numbers in the array you just created
r4, np.unique(r4)

(array([[9, 1, 3, 7, 4, 9, 3],
        [5, 3, 7, 5, 9, 7, 2],
        [4, 9, 2, 9, 5, 2, 4]]),
 array([1, 2, 3, 4, 5, 7, 9]))

In [36]:
# Find the 0'th index of the latest array you created
r4[0]

array([9, 1, 3, 7, 4, 9, 3])

In [37]:
# Get the first 2 rows of latest array you created
r4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [38]:
# Get the first 2 values of the first 2 rows of the latest array
r4[:2, :2]

array([[9, 1],
       [5, 3]])

In [39]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
b1=np.random.randint(0, 10, (3,5))
b2=np.ones((3,5))

In [40]:
# Add the two arrays together
b1, b2, b1+b2

(array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[ 7.,  8.,  3.,  1.,  4.],
        [ 2.,  8.,  4.,  2.,  6.],
        [ 6., 10.,  4.,  6.,  2.]]))

In [41]:
# Create another array of ones of shape (5, 3)
b3=np.random.randint(0, 10, (5,3))

In [42]:
# Try add the array of ones and the other most recent array together
#b2+b3

When you try the last cell, it produces an error. Why do think this is?

How would you fix it? Size difference bw arrays

In [43]:
# Create another array of ones of shape (3, 5)
b4=np.ones((3,5))

In [44]:
# Subtract the new array of ones from the other most recent array
b1-b4

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [45]:
# Multiply the ones array with the latest array
b1*b4


array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [46]:
# Take the latest array to the power of 2 using '**'
b1**2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [47]:
# Do the same thing with np.square()
np.square(b1)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [48]:
# Find the mean of the latest array using np.mean()
np.mean(b1)

np.float64(3.8666666666666667)

In [49]:
# Find the maximum of the latest array using np.max()
np.max(b1)

np.int64(9)

In [50]:
# Find the minimum of the latest array using np.min()
np.min(b1)

np.int64(0)

In [51]:
# Find the standard deviation of the latest array
np.std(b1)

np.float64(2.578543947441829)

In [52]:
# Find the variance of the latest array
np.var(b1)

np.float64(6.648888888888889)

In [53]:
# Reshape the latest array to (3, 5, 1)
b5=b1.reshape(3,5,1)
b5

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [54]:
# Transpose the latest array
b5.T

array([[[6, 1, 5],
        [7, 7, 9],
        [2, 3, 3],
        [0, 1, 5],
        [3, 5, 1]]])

What does the transpose do? It reverses the indexes

In [55]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
c1=np.random.randint(0, 10, (3,3))
c2=np.random.randint(0, 10, (3,2))

In [56]:
# Perform a dot product on the two newest arrays you created
c1.dot(c2), np.dot(c1, c2)
#c2.dot(c1), np.dot(c2, c1) this will give size error

(array([[16, 40],
        [14, 70],
        [14, 71]]),
 array([[16, 40],
        [14, 70],
        [14, 71]]))

In [57]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
c3=np.random.randint(0, 10, (4,3))
c4=np.random.randint(0, 10, (4,3))

In [58]:
# Perform a dot product on the two newest arrays you created
#c3.dot(c4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [61]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
c3.dot(c4.T)

array([[111,  57,  60, 105],
       [100,  52,  56,  96],
       [ 30,  37,  18,   4],
       [ 85,  42,  50,  87]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [62]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
d1=np.random.randint(0, 10, (3,3))
d2=np.random.randint(0, 10, (3,3))
d1, d2

(array([[6, 6, 8],
        [9, 9, 2],
        [6, 0, 3]]),
 array([[3, 4, 6],
        [6, 3, 6],
        [2, 5, 1]]))

In [63]:
# Compare the two arrays with '>'
d1>d2

array([[ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])

What happens when you compare the arrays with `>`?

In [66]:
# Compare the two arrays with '>='
d1>=d2

array([[ True,  True,  True],
       [ True,  True, False],
       [ True, False,  True]])

In [65]:
# Find which elements of the first array are greater than 7


In [ ]:
# Which parts of each array are equal? (try using '==')


In [ ]:
# Sort one of the arrays you just created in ascending order


In [ ]:
# Sort the indexes of one of the arrays you just created


In [ ]:
# Find the index with the maximum value in one of the arrays you've created


In [ ]:
# Find the index with the minimum value in one of the arrays you've created


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [59]:
# Create an array of normally distributed random numbers


In [60]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.